<?php

namespace SolutionForest\InspireCms\Listeners\Content;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use SolutionForest\InspireCms\Models\Contracts\SiteMap;
use SolutionForest\InspireCms\Support\InspireCmsConfig;

class GenerateContentSitemap implements ShouldQueue
{
    use InteractsWithQueue;

    public function handle(object $event)
    {
        $fullFilePath = InspireCmsConfig::get('routes.sitemap.file_path');

        if (! $fullFilePath) {
            throw new \Exception('Sitemap file path is not set in the config file.');
        }

        $this->ensureDirectoryExists($fullFilePath);

        $this->generateSitemap($fullFilePath);
    }

    protected function generateSitemap($fullFilePath)
    {
        $sitemapData = $this->getAllAvailableSitemapData();
        
        $xml = new \SimpleXMLElement('<?xml version="1.0" encoding="UTF-8"?><urlset/>');
        // $xml->addAttribute('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9');

        foreach ($sitemapData as $arr) {
            if ((! isset($arr['urls']) || empty($arr['urls'])) || ! isset($arr['lastmod']) || ! isset($arr['changefreq']) || ! isset($arr['priority'])) {
                continue;
            }
            $urlTag = $xml->addChild('url');

            $urlTag->addChild('loc', $arr['url']);
            $urlTag->addChild('lastmod', $arr['lastmod']);

            foreach ($arr['urls'] as $urlData) {

                if (! isset($urlData['url']) || empty($urlData['url']) || !isset($urlData['code']) || empty($urlData['code'])) {
                    continue;
                }

                $linkTag = $urlTag->addChild('xhtml:link');
                // $linkTag = $urlTag->addChild('xhtml:link', null, 'http://www.w3.org/1999/xhtml');
                $linkTag->addAttribute('rel', 'alternate');
                $linkTag->addAttribute('hreflang', $urlData['code']);
                $linkTag->addAttribute('href', $urlData['url']);
            }
            $urlTag->addChild('changefreq', $arr['changefreq']);
            $urlTag->addChild('priority', $arr['priority']);
        }
       
        $xml->asXML($fullFilePath);
        
        // Add comment to the end of the file
        $comment = "<!-- Generated by InspireCMS -->";
        file_put_contents($fullFilePath, $comment, FILE_APPEND);
    }

    protected function getAllAvailableSitemapData(): array
    {
        $records = InspireCmsConfig::getSiteMapModelClass()::with('model')->whereEnabled()->get();

       return collect($records)
            ->whereInstanceOf(SiteMap::class)
            ->map(fn (SiteMap $item) => $item->generateSitemapItem())
            ->toArray();

    }

    protected function ensureDirectoryExists($fullFilePath)
    {
        $directory = dirname($fullFilePath);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }
    }
}
