<?php

namespace SolutionForest\InspireCms\Generators;

use SolutionForest\InspireCms\Events\Content\SitemapGenerated;
use SolutionForest\InspireCms\InspireCmsConfig;
use SolutionForest\InspireCms\Models\Contracts\Sitemap;

class SitemapGenerator implements SitemapGeneratorInterface
{
    public function generateSitemapFile(): void
    {
        $fullFilePath = InspireCmsConfig::get('routes.sitemap.file_path');

        if (! $fullFilePath) {
            throw new \Exception('Sitemap file path is not set in the config file.');
        }

        $this->ensureDirectoryExists($fullFilePath);

        $this->generateSitemap($fullFilePath);

        event(new SitemapGenerated($fullFilePath));
    }

    protected function generateSitemap($fullFilePath)
    {
        $sitemapData = $this->getAllAvailableSitemapData();

        $xml = new \SimpleXMLElement('<?xml version="1.0" encoding="UTF-8"?><urlset/>');

        foreach ($sitemapData as $arr) {
            if ((! isset($arr['urls']) || empty($arr['urls'])) || ! isset($arr['lastmod']) || ! isset($arr['changefreq']) || ! isset($arr['priority'])) {
                continue;
            }
            $urlTag = $xml->addChild('url');

            $urlTag->addChild('loc', $arr['url']);
            $urlTag->addChild('lastmod', $arr['lastmod']);

            foreach ($arr['urls'] as $urlData) {

                if (! isset($urlData['url']) || empty($urlData['url']) || ! isset($urlData['code']) || empty($urlData['code'])) {
                    continue;
                }

                $linkTag = $urlTag->addChild('xhtml:link');
                $linkTag->addAttribute('rel', 'alternate');
                $linkTag->addAttribute('hreflang', $urlData['code']);
                $linkTag->addAttribute('href', $urlData['url']);
            }
            $urlTag->addChild('changefreq', $arr['changefreq']);
            $urlTag->addChild('priority', $arr['priority']);
        }

        $xml->asXML($fullFilePath);

        // Add comment to the end of the file
        $comment = '<!-- Generated by InspireCMS -->';
        file_put_contents($fullFilePath, $comment, FILE_APPEND);
    }

    protected function getAllAvailableSitemapData(): array
    {
        $records = InspireCmsConfig::getSitemapModelClass()::with('model.webSetting')
            ->whereEnabled()
            ->get();

        return collect($records)
            ->whereInstanceOf(Sitemap::class)
            ->map(fn (Sitemap $item) => $item->generateSitemapItem())
            ->filter(fn ($item) => ! empty($item))
            ->toArray();

    }

    protected function ensureDirectoryExists($fullFilePath)
    {
        $directory = dirname($fullFilePath);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }
    }
}
