<?php

use SolutionForest\InspireCms\Filament\Clusters\Content\Resources\PageResource;
use SolutionForest\InspireCms\Filament\Clusters\Settings\Resources\DocumentTypeResource;
use SolutionForest\InspireCms\Filament\Clusters\Settings\Resources\FieldGroupResource;
use SolutionForest\InspireCms\Filament\Clusters\Settings\Resources\FieldResource;
use SolutionForest\InspireCms\Filament\Clusters\Settings\Resources\LanguageResource;
use SolutionForest\InspireCms\Filament\Clusters\Settings\Resources\TemplateResource;
use SolutionForest\InspireCms\Filament\Clusters\Users\Resources\RoleResource;
use SolutionForest\InspireCms\Filament\Clusters\Users\Resources\UserResource;

// config for SolutionForest/InspireCms
return [

    'auth' => [
        'guard' => 'inspirecms',
    ],

    'avatar' => [
        'driver' => 'public',
    ],

    'cache' => [
        'languages' => [
            'key' => 'inspirecms.languages',
            'ttl' => 60 * 60 * 24,
        ],
    ],

    'filament' => [
        'enable_cluster_navigation' => true,
        'panel_id' => 'cms',
        'resources' => [
            'page' => PageResource::class,
            'document_type' => DocumentTypeResource::class,
            'field_group' => FieldGroupResource::class,
            'field' => FieldResource::class,
            'language' => LanguageResource::class,
            'template' => TemplateResource::class,
            'user' => UserResource::class,
            'role' => RoleResource::class,
        ],
    ],

    'models' => [
        'table_name_prefix' => 'cms_',
        'morph_map_prefix' => 'cms_',
    ],

    'override_plugins' => [
        'field_group_models' => true,
    ],

    'permissions' => [
        'skip_access_right_permission_on_resource' => false,
    ],

    'template' => [
        'path' => resource_path('views/inspire-cms/templates'),
    ],

    'resolvers' => [
        'user' => \SolutionForest\InspireCms\Resolver\UserResolver::class,
    ],

    'available_locales' => [
        'af',
        'ak',
        'am',
        'ar',
        'as',
        'az',
        'be',
        'bg',
        'bho',
        'bm',
        'bn',
        'bs',
        'ca',
        'ceb',
        'ckb',
        'cs',
        'cy',
        'da',
        'de',
        'de_CH',
        'doi',
        'ee',
        'el',
        'en',
        'eo',
        'es',
        'et',
        'eu',
        'fa',
        'fi',
        'fil',
        'fr',
        'fy',
        'ga',
        'gd',
        'gl',
        'gu',
        'ha',
        'haw',
        'he',
        'hi',
        'hr',
        'hu',
        'hy',
        'id',
        'ig',
        'is',
        'it',
        'ja',
        'ka',
        'kk',
        'km',
        'kn',
        'ko',
        'ku',
        'ky',
        'lb',
        'lg',
        'ln',
        'lo',
        'lt',
        'lv',
        'mai',
        'mg',
        'mi',
        'mk',
        'ml',
        'mn',
        'mni_Mtei',
        'mr',
        'ms',
        'mt',
        'my',
        'nb',
        'ne',
        'nl',
        'nn',
        'oc',
        'om',
        'or',
        'pa',
        'pl',
        'ps',
        'pt',
        'pt_BR',
        'qu',
        'ro',
        'ru',
        'rw',
        'sa',
        'sc',
        'sd',
        'si',
        'sk',
        'sl',
        'sn',
        'so',
        'sq',
        'sr_Cyrl',
        'sr_Latn',
        'sr_Latn_ME',
        'su',
        'sv',
        'sw',
        'ta',
        'te',
        'tg',
        'th',
        'ti',
        'tk',
        'tl',
        'tr',
        'tt',
        'ug',
        'uk',
        'ur',
        'uz_Cyrl',
        'uz_Latn',
        'vi',
        'xh',
        'yi',
        'yo',
        'zh_CN',
        'zh_HK',
        'zh_TW',
        'zu',
    ],
];
